### ISSUE TITLE
Rise Up! linux-lts 4.4.47 relased

### ISSUE THREAD

**Issue by jacksonatl** [archzfs/archzfs#103]

**Comment by KrzaQ** [comment]
Any chance of an ETA?

**Comment by demizer** [comment]
@KrzaQ I am working on converting the packages and build system to support extramodules so they only have to be updated once for a major version.

**Comment by demizer** [comment]
I'm actually going to continue pushing out packages for each kernel version for now. When #92 is implemented, it will need to be tested properly in order to guarantee the best I can that they new packages do not break anything. So for a time, there will be the standard kernel packages and the new "testing" packages.
