### ISSUE TITLE
new kernel releases

### ISSUE THREAD

**Issue by Kokokokoka** [archzfs/archzfs#105]
There was a problem with the latest update, the problem was that there was a 4.9.9 kernel already when this repo had 4.9.7 and 4.9.8, so there's a 4.9.10 kernel now, and 4.49 lts, could you please update
those modules to 4.9.10 and 4.49? As I struggle for 6.5.9 (as it has the case insensitive deadlock fixed) and still had no chance to upgrade from 4.8.13.

**Comment by storrgie** [comment]
I saw you report about 4.9.9 in #104 and I ignored it because it didn't make sense to me, as well as @demizer closed with a commit that resolved #104 properly.

You've created an ambiguous issue "new kernel releases", and maybe English isn't your first language... but you're babbling on about:

 - a problem with the update (zero context)
 - the existence of 4.9.9 (which is in testing)
 - requesting the 'modules' be updated to 4.9.10 (which isn't anywhere in arch right now unless you're using linux-mainline from the AUR)

Bud we know you're on arch, and its all fast moving and edgy... but I don't think asking for a dependent project to build modules weeks to months ahead of a kernel drop is reasonable.

I'd request that this issue be closed as it is a 'meta' request that isn't well thought out or even reasonable to ask of the project. @demizer is doing a damn good job of following the actual... you know.... core releases of the kernel, which happens pretty often. He is also working on #92 which may make that response time faster.

So, please open up tickets for actual problems. Otherwise leave a benevolent maintainer alone so that they can move the project forward as they see fit.

**Comment by Kokokokoka** [comment]
Ok, I'll close rhe issue, but I think that you're an offender, and didn't think your position through. As far as I know, the 4.9 is the new LTS and it's updated rather fast at least for now, and I'm talking about 4.9.10 as it's released in the kernel.org, officially, and .49 too, and they're both LTS, and, for example the 4.9.9
one has some cruicial fixes for my workflow, yes it's in testing, but that doesn't actually mean that's unstable, for a bleeding edge distributive this assumption sounds rather crazy as kernel is (at least for now) on of the most stable things in testing. 
My problem was that I didn't thing through enough, but the last time I've checked it was the 4.9.8 and now I forgot to remove the testing repository, that's my bad.
