### ISSUE TITLE
Support for kernel 4.11.6-3

### ISSUE THREAD

**Issue by ioquatix** [archzfs/archzfs#124]
Hello.

Firstly, let me say, thanks for all the work you do maintaining these packages. I use them and they are great, and have always been pretty reliable.

I'm just setting up a new home server and installing zfs fails because the current arch kernel version is 4.11.6-3 but these packages are for 4.11.6-1

Do you think it's possible to avoid tying this to the `pkgrel` version of the Linux kernel? I understand the value in tying it to the `4.11.6`, but perhaps it's okay to allow some flexibility within the `pkgrel`?

Thanks.
Samuel

**Comment by demizer** [comment]
Hello. You question has been answered many times, see the issue track search feature. Briefly, I was working on using extramodules support but I have limited time and haven't been able to get it working right. See the extramodules branch in the archzfs repo. I don't remember exactly where I left off, but I do remember I ran into problems with hardcoded kernel versions (including pkgrel versioning) in the zfs header files.

This issue is also similar to #118, so I'll close it as a duplicate. Thanks!

**Comment by ioquatix** [comment]
If this is a common question perhaps put it in the README. If all the issues are closed it might not be obvious even by searching.

**Comment by storrgie** [comment]
It is obvious if you search the issue tracker.

**Comment by ioquatix** [comment]
It's not obvious at all. I just tried searching. Not only am I not sure what I'm searching for, by default it only searches open issues, none of which seem relevant. I couldn't find any closed issues that seemed relevant. Please tell me what you were expecting me to search for and what I should have found. Yes, I did take a brief look for this particular issue by searching for "4.11.6-3", "4.11.6" and "pkgrel".
