### ISSUE TITLE
mkinitcpio always runs in check_initramfs

### ISSUE THREAD

**Issue by demizer** [archzfs/archzfs#153]
When building the test archiso, and after spl and zfs have installed, mkinitcpio is always running despite zfs hook not being defined in mkinitcpio.conf.

**Comment by minextu** [comment]
I think this is due to this pacman hook (https://git.archlinux.org/svntogit/packages.git/commit/?id=617173dcde960f00112ebdfee4c80ede71e67375)
I will always run `mkinitcpio` if any files in `/usr/lib/initcpio/` change, which happens when installing zfs-utils-common(-git). 
Might be something, that can't be fixed that easily.

**Comment by minextu** [comment]
Apparently you can overwrite a hook using a symlink to `/dev/null` in `/etc/pacman.d/hooks/<hook-name>` (https://bbs.archlinux.org/viewtopic.php?id=209793)
So you could run this in qemu, before installing zfs
```
# mkdir /etc/pacman.d/hooks
# # use on of these
# ln -s /dev/null 90-linux.hook
# ln -s /dev/null 90-linux-lts.hook
# ln -s /dev/null 90-linux-hardened.hook
```
