### ISSUE TITLE
Automounts not working until enabling zfs-import.target again

### ISSUE THREAD

**Issue by dmp1ce** [archzfs/archzfs#186]
I'm not sure where this issue should be reported, but after updating and rebooting I didn't have any of my ZFS mounts. I had to run `systemctl enable zfs-import.target`. I found a similar recent comment on the AUR. https://aur.archlinux.org/packages/zfs-utils-common-git/#news

How can this be prevented in the future? It is quite a scare to not have your data mounted when rebooting. Especially when services are relying on the data to be there.

**Comment by UweSauter** [comment]
I'm affected by this, too. What I see is ZFS trying to set "noop" scheduler for each disk (twice) but this has either been renamed to "none" or removed from the current kernel (4.13.11-1-ARCH).

```
# dmesg | grep ZFS
[    7.542672] ZFS: Loaded module v0.7.0-167_g23ea00a1f, ZFS pool version 5000, ZFS filesystem version 5
[    7.888263] ZFS: Unable to set "noop" scheduler for /dev/disk/by-id/wwn-0x5000cca222c6bbdd-part1 (sdk): 256
[…]
[    7.890195] ZFS: Unable to set "noop" scheduler for /dev/disk/by-id/wwn-0x5000c5002f5fe320-part1 (sda): 256
[    9.061482] ZFS: Unable to set "noop" scheduler for /dev/disk/by-id/wwn-0x5000cca222c689a0-part1 (sdg): 256
[…]
[    9.068215] ZFS: Unable to set "noop" scheduler for /dev/disk/by-id/wwn-0x5000c50032bd7522-part1 (sdb): 256
```

I suspect that zfs-import-*.service is taking longer that it used to due to that issue (in background) and zfs-mount.service is then already started when the pool actually comes online.

Could you check if you get the same warnings?

**Comment by Noctem** [comment]
Yeah, this bit me too. And it was especially a headache since my home directory (along with *.ssh/authorized_keys*) is on ZFS, fortunately I have physical access to the server.

**Comment by severach** [comment]
I used `systemctl preset zfs-import.target`
