### ISSUE TITLE
Upstream Encryption Format Change

### ISSUE THREAD

**Issue by minextu** [archzfs/archzfs#222]
https://github.com/zfsonlinux/zfs/pull/6864 just got merged upstream and changes the on-disk format of encrypted filesystems. 

We should warn about this before updating the git packages, since those datasets will mount read only and need to be migrated.

**Comment by minextu** [comment]
http://zfsonlinux.org/msg/ZFS-8000-ER#3 (`ZFS Errata #3`) has information on how to migrate existing encrypted datasets

**Comment by Redsandro** [comment]
I'm happy to learn this issue was closed. Well done everyone!

Looking forward to converting some encrypted datasets. Just waiting for the tagged release.

The `ZFS Errata #3` does confuse me a bit, although the problem is probably mine so please forgive my lack of more specific understanding for this mechanism:

> ```
> # zfs send test/crypt1 | zfs receive test/new_root/crypt1
> # zfs send test/crypt2 | zfs receive test/new_root/crypt2
> ```

All this time I've worked under the assumption that one can only `zfs send` a snapshot, and `zfs receive` one dataset, replacing the old dataset completely. The above looks like two entire datasets including snapshots are sent to distinct subdirectories of the new dataset. Is this legal? Is this new?

**Comment by minextu** [comment]
`zfs send` needs a fixed point to send from, so you need a snapshot most of the time. However, if the entire pool is mounted readonly or the given dataset is not mounted at all, you can in fact send without using a snapshot. But in this case you won't be able to use `-R`, so all snapshots and properties are lost in the process.
