### ISSUE TITLE
QUESTION - zfsonlinux and aur zfs-linux(-lts) - archzfs - stability

### ISSUE THREAD

**Issue by webdawg** [archzfs/archzfs#264]
I have been following the aur messages for quite some time now.  Can someone answer a question about the general stability of zfsonlinux and the archlinux zfs-linux?

I see a past message like this:  "A confirmed regression in 0.7.7 results in data loss during copy operations. So far, the issue has not been reported as reproducible on Arch Linux. The steps to reproduce are simple...."

On the AUR and I have data sets that I am moving over to the FreeBSD (FreeNAS) version of ZFS from openindiana because I feel that they work more testing into there releases.  I obviously use archlinux, so I know what I am asking here is a bad question, and I do see zfs-linux-lts, but even there we have some comments on performance (who knows if the message was warranted, there was not a lot of information provided).

I guess the only reason I am asking this question, is to ask the experts, the reliability of zfsonlinux in general, and the factors to keep in mind when combined with archlinux.

I have never used zfsonlinux, I may have messed with it years ago, but for a file system and LVM that was designed to protect data, I wonder when/if I should dig into using it for storing mission critical data.  I understand standard backup procedures are always critical, but at this point, I would like to keep this outside the scope of this conversation.

I would like to just understand the risk associated to moving into the ZFS linux world, and if someone has time to talk to me about it, that would be great.  Thanks!

**Comment by minextu** [comment]
zfsonlinux itself is quite stable and used by many in production. It's well tested, but sometimes bugs get through anyways. The regression you were talking about is the worst bug I know of, since I have started using zfsonlinux. But even this bug wasn't that tragic, since you got an error message / bad return code, so data wasn't silently lost (unlike some bugs in btrfs). I have never experienced data loss with zfsonlinux or archzfs. I haven't used zfs for that long though.

As for archzfs specifically, the worst bugs I know of were things like missing systemd services, so auto mounting didn't work after boot. Or having a non-functional package for non LTS kernels. In both of these cases, fixed packages were pushed relatively fast, and downgrading, while annoying, was an option.

So as long, as you do backups and are prepared to have some update problems / downtime's from time to time,  which can happen on archlinux anyways, you should be good.

There are many blog posts out there of people, who have more experience with zfsonlinux than me. You might want to read some of them.

As the new maintainer of archzfs, I want to automate testing to improve the speed of updates and have more stable packages to prevent most bugs in the future.

**Comment by webdawg** [comment]
Thanks for the reply.
