### ISSUE TITLE
Can zfs-git be agnostic of kernel versions?

### ISSUE THREAD

**Issue by crocket** [archzfs/archzfs#28]
I don't want to wait for others to build zfs against new linux packages.
It'd be better if zfs-git is agnostic of kernel versions.

**Comment by afics** [comment]
@demizer I'd like to do the former (specifically with linux-grsec). Have you tried zfs on a grsec kernel?

**Comment by demizer** [comment]
@afics Nope

**Comment by dasJ** [comment]
Yes, I am building ZFS myself using Jenkins. It would be really nice to be able to rebuild at any time, because the build is getting triggered by kernel updates as well.

**Comment by dasJ** [comment]
I'm having exactly that problem now. They rolled out a new kernel and now the dependcies are too old:

```
warning: cannot resolve "linux=4.3.3-2", a dependency of "spl-git"
```

Will I break my system if I just change the required version in the PKGBUILD?

**Comment by demizer** [comment]
This should now be sort of fixed, I added min max version numbers to the PKGBUILDS: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=zfs-linux#n22

If you are upgrading minor versions there will be no issues. Major versions will still give trouble because of the max version dependency on the "linux" package for the kernel. I always add any packages I build to a local package repository, so I never have these issues. To avoid these issues, please either use the archzfs package repo, the dkms packages, or maintain your own local arch linux package repository.

As for supporting multiple kernels, the ZFS packages are tied to the kernel they are built for. This is the nature of kernel modules. So there can never be a single zfs package for all the different kernel packages in Arch Linux. Each kernel package will need it's own zfs packages. I have changed the names of the packages I maintain in AUR to include the names of the kernel they target to hardcode this fact.

So, if archzfs does not support your favorite kernel package, please open a new issue and I may possibly add support for that kernel. Including pre-built packages and package sources pushed to AUR when kernel versions are changed.

**Comment by demizer** [comment]
We had an "Oops" that I neglected to consider. Setting the max kernel version means that users can upgrade their kernels, but since ZFS is tied to the kernel version, this caused broken ZFS file systems because the installed ZFS is only usable with kernel 4.5.1.

Using a max kernel version did nothing to solve the OPs problem.

I have returned the packages to using hard set "linux=4.5.2".

I do now have an official stance, anyone using the archzfs packages should either use the archzfs.com repo or maintain their own local repo. Building from AUR and not using a local package repository just doesn't work.

If anyone has a suggestion, please feel free to suggest!
