### ISSUE TITLE
ZFS on Linux version 0.8.0 released

### ISSUE THREAD

**Issue by fryfrog** [archzfs/archzfs#293]
The ol' 0.8.0 is out...

https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.8.0

**Comment by minextu** [comment]
Update has been pushed, Thx!

**Comment by fryfrog** [comment]
```
1 ✗ fryfrog@cain ~ $ sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 archzfs is up to date
:: Starting full system upgrade...
:: Replace spl-linux with archzfs/zfs-linux? [Y/n] y
resolving dependencies...
looking for conflicting packages...
:: zfs-utils and spl-utils are in conflict. Remove spl-utils? [y/N] y

Package (4)        Old Version             New Version            Net Change  Download Size

spl-linux          0.7.13_5.1.4.arch1.1-1                          -0.12 MiB
spl-utils          0.7.13-1                                        -0.06 MiB
archzfs/zfs-linux  0.7.13_5.1.4.arch1.1-1  0.8.0_5.1.4.arch1.1-1    0.25 MiB       0.97 MiB
archzfs/zfs-utils  0.7.13-1                0.8.0-1                  2.44 MiB       4.43 MiB

Total Download Size:    5.40 MiB
Total Installed Size:  15.70 MiB
Net Upgrade Size:       2.51 MiB

:: Proceed with installation? [Y/n] y
```

Just a quick confirm, `spl-linux` was merged into `zfs-linux`?

**Comment by minextu** [comment]
Yep that's right

**Comment by MarianArlt** [comment]
Is there some BIG HUGE announcement for this? I feared to destroy zfs on my system when this came up.

**Comment by fryfrog** [comment]
It's on their front page and reddit is very excited about it. Is that good enough?

**Comment by MarianArlt** [comment]
First off: No offense please. I think it's a valid point.
Second: I suppose you are referring to the oneliner in the 0.8.0 release tag on ZOL github? Honestly as an Arch user I come here first. I had to find this thread to finally make a decision when prompted by pacman whether or not to remove spl-utils.
There could have simply be a pacman message about how spl-utils was deprecated and safe to remove.

I feel that it's become common to not document impacting updates at all. I know it's a nuisance to keep track of documentation. But this is quite a change (a good one indeed).
Also I don't read reddit at all and I don't think it's a valid source for documentation.
Again this is no personal offense at all. I'd just like to see better overall update documentation for great programs at their respective sources.

**Comment by fryfrog** [comment]
I've had packages replace other packages a handful of times in my Arch history and literally none of them have output spew saying anything about it. I don't think it is even *possible* at the point where you're prompted to make the choice, the package only gets to echo things once it is being instaleld. Can you point out any examples of packages that do this? I doubt there are any based on my experience w/ Arch and from working on other packages.

And what do you mean by documenting updates? These are packages built pretty much directly from *upstream*, this is where you'll find documentation and announcements and things like that. Can you point out some other Arch packages that do what you're talking about? I don't know of any, haven't seen anything like that in my usage.

**Comment by fryfrog** [comment]
https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.8.0

^ And what do you mean by *one liner*? The release notes for it are *huge* and fairly detailed.

**Comment by MarianArlt** [comment]
I didn't want to make you feel like having to argue about who should be responsible for documentation. If your statement is "upstream" than that's that. Fair enough.

The PKGBUILD pkgname.install script has a pre_upgrade function. Would that allow to printf/echo to the shell? (Just out of curiosity, I don't maintain any packages)
It's true that usually there are no informative prints when using pacman. In AUR it's not unusual though and I think it's a lacking feature of pacman packages.

From Arch Wiki:

    ## arg 1:  the new package version
    ## arg 2:  the old package version
    #pre_upgrade() {
        # do something here
    #}

Thanks for porting ZOL :)

**Comment by fryfrog** [comment]
To be clear, I'm not the owner or maintainer of this package or repo.

Nothing in the PKGBUILD or `.install` gets run *before* the package gets installed, so it wouldn't help w/ the X replacing Y prompt. You'd still be doing it blindly.

And nobody puts changelog / release notes in there for good reason. They'd only be reasonably visible if that package was the last one to install. Echoing stuff from packages is generally frowned on.

**Comment by minextu** [comment]
We have used  `post_upgrade` messages before, but only if there's something that needs manual intervention (like renamed system services, breaking encryption). 
But like @fryfrog said: it will only display those messages after it has already been installed.

Right now I only know of two other ways to reach archzfs users: Create an issue in this repository, or submit a comment to one of the packages in the aur. If you have any suggestions where to put news like this in a more prominent way, let me know.

Though I probably should have used `replaces` instead of `conflicts` to get a less frightening message.

**Comment by MarianArlt** [comment]
@fryfrog Thanks for point that out
@minextu Thanks for taking your time to comment, that's very much appreciated! 

I studied design, I use to develop more than I design and I maintain products myself. I know it's annoying to keep track of documentation. I'm now in my mid thirties. Call me old school but I think a prominent sentence in the README of this repo (delete it later) would be enough to say: "We told you!" ;) After all this is the ZFS package used by a lot of distros based on Arch.
I know there's a rather (to me weird) philosophy about how README's should be only about the general usage of a product. Definitely the choice of each creator.

In this very case it made me want to comment because ZFS gets updated with every kernel anyways, so usually I do not follow the ZOL changelog carefully. I'm just a dumb user, I come here ;) There's also a VERY huge philosophical implication behind this on whether or not people need to be investigative when it comes to documentation.

I think your comment about the script flag is spot on and would have indeed avoided some confusion! Thank you again for the constructive message.
