### ISSUE TITLE
Replicating your setup on another host

### ISSUE THREAD

**Issue by spheenik** [archzfs/archzfs#341]
Hi,

not really a bug, rather than a request for more info. I am using archzfs for quite some time now, and am very happy with it, but I've developed the urge to have a kernel whose config differs from what arch offers (basically XanMod from AUR). 

I am contemplating taking your setup to my server and build the additional kernel there, so that my client machine does only need to pull the completed binary of the kernel and ZFS.

Would that be feasible? Could you describe a bit what has to be done to deploy this on a server, and how much time you have to spend running it?

Thank you!

**Comment by minextu** [comment]
Hey,

Yes it's definitely possible. The first step would be getting archzfs to work on your local machine (https://github.com/archzfs/archzfs/wiki/Building-archzfs). 

After that you can add your kernel to the buildscripts by copying one of the existing kernel configurations (i.e. `src/kernels/linux-lts.sh`).
Adjust the specific parts of your kernel (all references to `linux-lts`).

The first few lines in `get_kernel_options()` are there to check what the latest kernel version is. 
You need add your on code here that returns the full kernel version. Take a look at the `linux-vfio.sh` kernel configuration for a alternative implementation (repo based instead of website based).

After you have done all of that, test your configuration by running `./build.sh update custom` (replace custom with what you set `mode_name` to). This will create a PKGBUILD in `packages` that you can inspect. If everything looks right, build it by running `./build.sh make custom`. The final package will be saved in the same directory as the PKGBUILD.

Now that everything is building, follow the instructions here and get the buildbot working: https://github.com/archzfs/archzfs-ci. Adjust `conf.env` to point to your fork of archzfs where you pushed the new kernel configuration. You probably also want to look at the `Automated Deployment` of the readme.

The main configuration for the ci system is in `master/config/master.cfg`. Add you kernel to line 11 (maybe remove the other ones). You might need to add a custom repo in the `Dockerfile` in `/worker` if your linux package is not in the official repositories (or compile the kernel with the buildscripts too).
Run `docker-compose build` to rebuild everything.

Let me know if you have any more questions and good luck :slightly_smiling_face:

**Comment by spheenik** [comment]
Wow very comprehensive. Thanks a bunch! Will try this soon, and keep you updated!
