### ISSUE TITLE
Move from *-git packages to plain zfs/zfs-utils/spl/spl-utils

### ISSUE THREAD

**Issue by chungy** [archzfs/archzfs#43]
ZoL has a new stable-branch maintainer, being a lot better about maintaining compatibility with current kernels than ZoL has been historically. I don't think this package has actually used a non-release commit in quite a long time. Perceptually, I think moving away from zfs-git (et al) would improve an image of using only the release tags. It would probably also make it easier for the daring to use actual *-git builds from the master branches of each ZoL project.

**Comment by demizer** [comment]
I agree. Upstream has been very good about keeping up with the latest kernel releases. Particularly in the last year. I will have to get in contact with the stable branch maintainer and make sure the Arch environment is understood so we don't run into the issues we were having a 1.5+ years ago. Then we can move back to having zfs-git really mean latest git HEAD instead of just being the last git commit that works with arch's kernel version.

**Comment by chungy** [comment]
Has there been any progress on this?

**Comment by demizer** [comment]
None at all. I have been strapped for time lately and have not spent much time
on anything other than work, but we really need to do this. I will spend some
time this weekend on this hopefully.

  

Thanks for the poke!

On Apr 14 2016, at 2:46 pm, Mike Swanson &lt;notifications@github.com&gt;
wrote:  

> Has there been any progress on this?

>

> —  
You are receiving this because you commented.  
Reply to this email directly or [view it on GitHub](https://github.com/archzfs
/archzfs/issues/43#issuecomment-210166701)![](https://github.com/notifications
/beacon/AAB1U-_2AaYdNGTqyt77SkYqTJVW8kE4ks5p3rW9gaJpZM4GFppS.gif)

**Comment by demizer** [comment]
I have the build scripts refactored for building the standard zfs packages and have pushed https://aur.archlinux.org/packages/zfs/ at least.

Unfortunately, the names for zfs-utils, spl, spl-utils packages have already been taken in AUR for the DKMS packages. I have sent emails to the maintainers of these packages asking if they could rename their packages and offering my help to do so.

**Comment by demizer** [comment]
This is complete.

The git packages now pull from HEAD of the master branch of upstream. The non-git packages now use the stable releases.

Packages in AUR now also include the kernel package they target as part of the name. ZFS packages for the default "linux" packages of Arch Linux are named "zfs-linux" and "zfs-linux-git".

Thanks!

**Comment by chungy** [comment]
Thanks, I love the solution that you implemented, it works quite well I think.
