### ISSUE TITLE
Preserve more version for old arch iso

### ISSUE THREAD

**Issue by zoritle** [archzfs/archzfs#448]
There are many arch derivatives which have different release schedule,  and thus behind the kernel version of latest arch iso. Many of these iso provided by derivatives using arch repo and include full desktop environment, thus very useful for install/repair pure archlinux.

BTW, another question I'm curious, what prevent this project to upstream to arch repo? I understand that the zfs module can't be included inside kernel binary, but separately distribute as a module seems no problem according to [Ubuntu](https://ubuntu.com/blog/zfs-licensing-and-linux) . If zfs module can be included in arch official repo, thus shipped with iso and other user space tools can also be included, working with zfs be so much easier.

**Comment by stevleibelt** [comment]
@zoritle what do you want to achieve with your issue ticket. From reading, there are multiple options:

* Preserve more version for old arch iso (taken form the title), but what do you want exactly?
* Build arch iso files for all the arch derivatives out there?
* Convince the official arch people to ship an arch iso with the zfs module included?

Building an arch iso with zfs module inside is not complicated. I am the creator and maintainer of the [arch-linux-live-cd-iso-with-zfs](https://github.com/stevleibelt/arch-linux-live-cd-iso-with-zfs) build script which is working fine.

Because of the pure amount of webspace and the rolling release nature of arch, I am only keeping the last successful iso. I don't see a reason to keep even older iso files. I've already fixed an more than six month not updated system with my iso, so this is working.

Why do you think it is useful to keep older arch iso files? And would you offer webspace to do so?

Best regards,
Stev
