### ISSUE TITLE
NVIDIA drivers support

### ISSUE THREAD

**Issue by BlueskyFR** [archzfs/archzfs#467]
Hi!

The nvidia arch package depends on specific Linux versions, so it is completely broken while using the archzfs repo.
Could support for the nvidia drivers be provided in a specific repo?

**Comment by stevleibelt** [comment]
@BlueskyFR maybe I am wrong but this would indicate that the archzfs-team has to fully maintain a specialized NVIDIA driver package.

Would you be so kind and explain what "completely broken" means?

Best regards,
Stev

**Comment by BlueskyFR** [comment]
Sure,
AFAIK, NVIDIA drivers are built for a specific kernel version, which is why archzfs has a repo for the Linux kernel.
When using the `nvidia` package, which assumes the latest kernel is installed, the installation is then broken since modules can't load properly.

**Comment by stevleibelt** [comment]
When I read this, I get the impression, that this is the common issue we, as zfs users, already have.

[My system update](https://github.com/stevleibelt/shell_config/blob/master/_source/function/packagemanager/generic#L27) bash function handles this issue already.
Since the zfs packages always requires a special kernel version, I simple update all [except kernel- and zfs related packages](https://github.com/stevleibelt/shell_config/blob/master/_source/function/packagemanager/generic#L99) until I hit the right time where zfs packages and kernel version are in an ideal state.

We simple can not upgrade the kernel as long as OpenZFS has not adapted to the latest kernel. What you can do is to use [DKMS](https://wiki.archlinux.org/title/ZFS#DKMS) with all its impact.

Best regards,
Stev

**Comment by BlueskyFR** [comment]
The kernel can be updated at all time without the need of blacklisting anything in `pacman.conf` when using `kernels.archzfs.com`, so there is no such deal as waiting for zfs and kernel versions to match.

My proposal is to solve the same problem for NVIDIA drivers

**Comment by stevleibelt** [comment]
> The kernel can be updated at all time without the need of blacklisting anything in pacman.conf when using kernels.archzfs.com, so there is no such deal as waiting for zfs and kernel versions to match.

Wasn't aware of that, thank you!

Bonus, I bet now the maintainers know what you want :-).

**Comment by ArnCo** [comment]
I am not a maintainer, but I think that I understand your problem. However, it is not the role of this repo to "fix" your NVIDIA installation.

Here are a few hints to understand what happens here, as I think that your are missing some key concepts.

> AFAIK, NVIDIA drivers are built for a specific kernel version, which is why archzfs has a repo for the Linux kernel.

No. Archzfs does not have a repo for the Linux Kernel. Archzfs provides binary packages of the zfs module for several kernels, including the default linux (latest), linux-lts and linux-zen. Archzfs does not compile the kernel, **it compiles a module for the kernel**, the zfs module.

Here is what happens in your case:
- Your NVIDIA driver is indeed built for the latest linux kernel.
- Your current linux kernel may be held back because of the current version of your zfs-archlinux binary package, which is built for an earlier kernel than your NVIDIA package. Indeed, the maintainer of the Archzfs repository has to manually force a bump to build a new zfs-linux package for the latest kernel, which may be delayed for some reason. That happens.

To circumvent your issue, you can install zfs-dkms from this repo or the AUR. This package will allow you to build the zfs module for your latest kernel (this will be done every time your kernel is updated through pacman), and you will be able to install your nvidia driver which is already built for the latest kernel.

Last piece of advice: install linux-lts as a fallback, as zfs-dkms sometimes fails to build with the newer kernels, as archlinux is quite aggressive regarding their kernel update policy. If you do that, you will also have to install nvidia-dkms, so that your nvidia is built for the LTS kernel as well.

IMHO this issue can be closed.

**Comment by ArnCo** [comment]
I am not a maintainer, but I think that I understand your problem. However, it is not the role of this repo to "fix" your NVIDIA installation.

Here are a few hints to understand what happens here, as I think that your are missing some key concepts.

> AFAIK, NVIDIA drivers are built for a specific kernel version, which is why archzfs has a repo for the Linux kernel.

No. Archzfs does not have a repo for the Linux Kernel. Archzfs provides binary packages of the zfs module for several kernels, including the default linux (latest), linux-lts and linux-zen. Archzfs does not compile the kernel, it compiles a module for the kernel, the zfs module.

The kernels.archzfs.com is a semi-official project that seems linked to the archzfs repo, but not actively maintained (no commit for two years) which aims to maintain compatibility with the installed kernel and the current archzfs package versions, by holding the version back. Please see [https://end.re/blog/ebp036_archzfs-repo-for-kernels/](https://end.re/blog/ebp036_archzfs-repo-for-kernels/).

Here is what happens in your case:

- Your NVIDIA driver is indeed built for the latest linux kernel.
- Your current linux kernel is held back because of the current version of your zfs-archlinux binary package, which is built for an earlier kernel than your NVIDIA package. Indeed, the maintainer of the Archzfs repository has to manually force a bump to build a new zfs-linux package for the latest kernel, which may be delayed for some reason. That happens.
- If you are trying to install the nvidia package for the first time, there is a kernel version mismatch, and the installation fails.

To circumvent your issue, you can install zfs-dkms from this repo or the AUR. This package will allow you to build the zfs module for your latest kernel (this will be done every time your kernel is updated through pacman), and you will be able to install your nvidia driver which is already built for the latest kernel.

Last piece of advice: install linux-lts as a fallback, as zfs-dkms sometimes fails to build with the newer kernels, as archlinux is quite aggressive regarding their kernel update policy. If you do that, you will also have to install nvidia-dkms, so that your nvidia is built for the LTS kernel as well.

IMHO this issue can be closed.
