### ISSUE TITLE
why are you providing zfs 2.2.4 for kernel 6.9.x?

### ISSUE THREAD

**Issue by mabod** [archzfs/archzfs#538]
zfs 2.2.4 is not compatible with kernel 6.9.x but yet archzfs provides a package like `zfs-linux 2.2.4_6.9.6.arch1.1-1`
The PKGBUILD  does not seem to pull any specific patches to ensure 6.9 compatibility. 

Just one example about missing patches:  https://github.com/openzfs/zfs/pull/16282

And we dont know what else might be missing until zfs 2.2.5 is released.
Isnt it pretty risky to provide tha zfs-linux package at this point in time?

**Comment by darkbasic** [comment]
I completely agree. I do not use this repo but I was looking into doing so and I immediately changed my mind as soon as I saw you shipped unpatched 2.2.4 for kernel 6.9. I recently experienced [data corruption with 6.8](https://github.com/openzfs/zfs/issues/15930) due to the same reason (early compatibility patches known to not pass the test suite) and it's known since day one that zvol is broken on 6.9.

**Comment by jbrodriguez** [comment]
@darkbasic do you have an alternative in order to use zfs on archlinux ? or you switched distro ?

**Comment by a-v-g-s** [comment]
Alternative is to use linux-lts.
The process isn't great because the repo is so rarely in sync; but essentially I used `downgrade` to install linux-lts 6.6.35-2, then installed zfs-linux-lts, then regenerated the initrd.

**Comment by mabod** [comment]
Using linux-lts is the only option.

**Comment by darkbasic** [comment]
@jbrodriguez I backport the required patches in order to make it work safely with latest kernel

**Comment by darkbasic** [comment]
I'm building my own [zfs-dkms-staging-git](https://aur.archlinux.org/packages/zfs-dkms-staging-git) and my own [zfs-utils-staging-git](https://aur.archlinux.org/packages/zfs-utils-staging-git).

**Comment by mabod** [comment]
But even if your are building your own zfs module you are not sure if you are missing something. The patch I have linked in my opening post is 2 weeks old. If you have install zfs on kernel 6.9 before that time you did not even know that you are missing that patch because it simply did not exist. 

If you are building the zfs module forkernel 6.9 now, with all currently available patches, you still do not know if that is all of it. May be next week there is a another patch. 

You can only be sure if zfs is officially released for the new kernel. Everything else is just gambling.

**Comment by michaelbeaumont** [comment]
@mabod do you by any chance if there's an upstream issue tracking 6.9 compatibility/when it will be officially released? I can't find anything at https://github.com/openzfs/zfs

**Comment by kido5217** [comment]
> Using linux-lts is the only option.

I would recommend linux-lts with zfs's dkms package.

**Comment by darkbasic** [comment]
> The patch I have linked in my opening post is 2 weeks old. If you have install zfs on kernel 6.9 before that time you did not even know that you are missing that patch because it simply did not exist.

> You can only be sure if zfs is officially released for the new kernel. Everything else is just gambling.

I did know of the need for such patch even before 6.9 got released because the test suite for zvol was failing against 6.9. In fact I kept using 6.8 for a little longer and finally decided to upgrade but stop using zvol for some time.
I wouldn't call it gambling because you have some guarantees from the test suite: it didn't pass when I upgraded to 6.8 and I've got data corruption because of it.
I wouldn't call it safe either, but I'm confident enough to still use it.
I definitely don't like the fact that archzfs doesn't backport patches and keeps using versions known to not pass the test suite: it's a recipe for data corruption.

**Comment by darkbasic** [comment]
@jbrodriguez the patch has been backported into [zfs-dkms-staging-git](https://aur.archlinux.org/packages/zfs-dkms-staging-git)

**Comment by n0xena** [comment]
What is your pool layout and your workload?
I use a 8x 3tb raidz2 as direct attached pool to my main gaming rig and although sometimes I have some loading stutters/lags in games with big assets (as I don't have a SSD as arc2) I not got any bit-flip neither in my regular datasets nor in my zvols.

**Comment by gentoosys** [comment]
I am building kernel myself (incl zen and other patches) with linux-tkg scripts and using zfs-dkms. I am using only last supported kernel, now 6.8.12, and watch rss feed with zfs releases. When new release come, I am compiling new kernel. This is best and safe way for me I found. 
P.S. Hope one day they will change their f license to GPL and merge zfs to kernel tree.

**Comment by reaperx7** [comment]
I have zfs-dkms-2.2.4 and utils built against the 6.9.9-zen kernel just fine. As far as I've been able to read within the linux changelogs, there was no change to the code that  would affect how file systems operate, including ZFS. 6.9.x kernels should be safe to use.

**Comment by michaelbeaumont** [comment]
Looks like openzfs has [finally declared compatibility](https://github.com/openzfs/zfs/pull/16358). Might be time to close this issue but I think there needs to be a discussion on when/how to provide zfs for the newest kernel on Arch.

**Comment by soi1uhtgnei2urtonwe4u** [comment]
>why are you providing zfs 2.2.4 for kernel 6.9.x?

Very good question. If the definition of the `zfs-dkms` package is blindly trying to install, then that's ok and it's up to the user. Otherwise there needs to be e.g. a Linux version check, like:

>Your Linux version (6.9) is newer than what is officially supported by this OpenZFS v2.2.4 build (6.8). It's not recommended to continue the installation. Do you want to continue? [y/N]

---

>I have zfs-dkms-2.2.4 and utils built against the 6.9.9-zen kernel just fine.

Just because it builds against a newer Linux version doesn't mean one should do it. You better have backups when you play like this.

**Comment by reaperx7** [comment]
We do need 2.2.5 tested and verified for 6.10.x as stable. The kernel updates have been pouring in as of late, so I am guessing development has been hectic for OpenZFS to keep up.

**Comment by darkbasic** [comment]
If you use the zfs-dkms aur package that commit has been backported since a long time.

**Comment by n0xena** [comment]
request for close - outdated
