### ISSUE TITLE
Additional packages for SSD TRIM branch

### ISSUE THREAD

**Issue by farnoy** [archzfs/archzfs#55]
Hi, could we get additional versions built&published for the branch supporting TRIM?

We'd need packages like `spl-trim-git`, `zfs-utils-trim-git` etc.

**Comment by demizer** [comment]
Looks like TRIM/DISCARD is still a work in progress with much activity going on at 

https://github.com/zfsonlinux/zfs/pull/3656

some additional links:

https://github.com/zfsonlinux/zfs/pull/1016
https://www.illumos.org/issues/6363

I don't have the bandwidth to support this currently. Seems like in order to use TRIM, there will be some patching needed. There will likely be problem for people due to the complexity of the change.

I will be closing this ticket, but if someone wants to be the owner, and get TRIM/DISCARD packages in the archzfs repo that's fine with me!

Thanks!
