### ISSUE TITLE
Auto-generate conflicts for packages

### ISSUE THREAD

**Issue by demizer** [archzfs/archzfs#75]
It is not possible to have multiple archzfs package groups installed at the same time. Right now we only have three: archzfs-linux, archzfs-linux-git, and archzfs-linux-lts. But as archzfs grows to support more kernels, these list in each of the PKGBUILD will become difficult to manage. So we should auto-generate the list of conflicts.

**Comment by null-git** [comment]
Do you mind giving a short explanation why it's impossible to install multiple archzfs package groups at the same time? I'm using the archzfs repository on my primary machine and would love to have some fallback to linux-lts with working zfs in case something goes wrong.

As far as I can tell from the installed files the conflict is mainly because of the header files in usr/src/{spl,zfs}-<versionnr>/include/, which could maybe just be put into another zfs-linux-headers package (as a quick diff didn't show any difference between them)? All the other files seem to have their kernel version in the path and could probably be installed side by side?

**Comment by demizer** [comment]
Mostly because I have not had a lot of time to work on it. If you want to
open a ticket for this on github.com/archzfs/archzfs that would be great.

On January 29, 2017 at 7:14:50 AM, Jonas Palm (notifications@github.com)
wrote:

Do you mind giving a short explanation why it's impossible to install
multiple archzfs package groups at the same time? I'm using the archzfs
repository on my primary machine and would love to have some fallback to
linux-lts with working zfs in case something goes wrong.

As far as I can tell from the installed files the conflict is mainly
because of the header files in usr/src/{spl,zfs}-/include/, which could
maybe just be put into another zfs-linux-headers package (as a quick diff
didn't show any difference between them)? All the other files seem to have
their kernel version in the path and could probably be installed side by
side?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/archzfs/archzfs/issues/75#issuecomment-275913049>, or mute
the thread

**Comment by demizer** [comment]
Mostly because I have not had enough time to work on it.

**Comment by demizer** [comment]
Work is in progress to fix this by adding "spl-linux-headers" and "zfs-linux-headers" packages. Thanks @null-git
