### ISSUE TITLE
Can't get Arch to boot with zfs-linux 4.7.4-1 - Failed to mount the real root device

### ISSUE THREAD

**Issue by johnramsden** [archzfs/archzfs#79]
Since the zfs-linux 4.7.4-1 update I can't get my system to boot. it stops at 

```
 Failed to mount the real root device
Bailing out, you are on your own. Good luck. 
```

But when I checked, the pool is actually mounted and accessible, the system is just not booting.

I had everything working fine before this update, so I'm not sure what's different. 

The system I'm having trouble with is set up the same way I always have it up like this: 

``` 
zfs list
NAME                 USED  AVAIL  REFER  MOUNTPOINT
vault                854M   228G    96K  none
vault/ROOT          6.83M   228G    96K  none
vault/ROOT/default  6.74M   228G  6.74M  legacy
vault/home           100K   228G   100K  /home
vault/tmp             96K   228G    96K  /tmp
vault/usr            590M   228G   590M  legacy
vault/var            256M   228G   256M  legacy 
``` 

I have attempted booting into a live disc and setting the cachefile, i've also made sure zfs.target and zfs-import-cache.service is enabled. 

This system is running grub with the following configuration: 

``` 
menuentry "Arch Linux" {
    linux /vmlinuz-linux zfs=vault/ROOT/default rw
    initrd /intel-ucode.img /initramfs-linux.img
} 
``` 

I've tried booting into the live iso and setting different things at least 10 times and I'm not sure where to go from here. I even tried an entire reinstall and got the same issue at boot.

**Comment by johnramsden** [comment]
Well I found "a solution", the pool will not mount legacy, but will mount managed by ZFS. This is odd because it has always worked for me in the past, i'm not sure what the update changed.

**Comment by charlyhoteltango** [comment]
As i was comparing the hook scipts vom version 0.6.5.7 and 0.6.5.8 i saw there were quite many changes. 

I managed to get it now running on my machine with legacy mountpoint on my root dataset and overall a similar setup like @johnramsden (I followed his tutorial - Thanks for that).

I tried to keep the installed scripts as they are but with no success. In order to get my system booting again i had to edit the file at /usr/lib/initcpio/hooks/zfs.
At line 57 it says:
`local tab_file="${node}/etc/fstab"`
and changed it to:
`local tab_file="/etc/fstab"`

In order to make this working I had to add the fstab file to the mkinitcpio.conf within the FILES section:
`FILES="/etc/fstab "`

Don't forget to also activate the systemd services as described here [https://github.com/zfsonlinux/zfs/releases](https://github.com/zfsonlinux/zfs/releases) with
`systemctl preset zfs-import-cache zfs-import-scan zfs-mount zfs-share zfs-zed zfs.target`

And finally there were also some changes within /usr/lib/initcpio/install/zfs where the installer doesn't include the hostid file any more so I did it by adding the kernel parameter spl.spl_hostid=0xHOSTID (maybe this could have been also solved by adding the hostid file to the initramfs as i did with fstab - didn't test this solution).

Finally run `mkinitcpio -p linux` and you should be good to go with your legacy mountpoint setup.

**Comment by johnramsden** [comment]
Yea, I was able to get it working by making sure the services were properly enabled, thanks.
